extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - prettier
  - prettier/react
plugins:
  - react
parser: "babel-eslint"
parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
  browser: true
settings:
  react:
    version: "16.8"
