extends:
- "eslint:recommended"
- "plugin:react/recommended"
- prettier
- prettier/react
plugins:
- react
parser: "babel-eslint"
parserOptions:
  sourceType: "module"
env:
  es6: true
  node: true
  browser: true
