# Must set
# + $GITHUB_TOKEN

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: node_js

# Caching so the next build will be fast too.
cache:
  directories:
    - "node_modules"

# Ensure necessary system libraries are present
node_js:
  - "lts/*"

script:
  - npm test
  - npm run build

deploy:
# Deploy updated docs to github pages
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target-branch: master
  on:
    branch: production

